import { VillaProps } from "../components/villas/types";

export const villasData: VillaProps[] = [
  {
    id: 1,
    title: "Lakeside Estate",
    location: "Greater Accra • Lakeside",
    coordinates: { lat: 5.726743173934811, lng: -0.1200319741836416 },
    price: 2000,
    guests: 4,
    bedrooms: 3,
    hasPool: true,
    bathrooms: 5,
    image: "/Lake1.jpg",
    images: ["/Lake1.jpg", "/Lake2.jpg", "/Lake3.jpg", "/Lake4.jpg"],
    description:
      "Experience comfort, privacy, and elegance in this beautifully furnished apartment located in the serene and secure Lakeside Estate.",
    amenities: [
      "Free Wi-Fi",
      "Kitchen",
      "Pool",
      "Well-furnished hall",
      "Television in all rooms",
      "PS5 Gaming Console",
    ],
    rates: [
      { option: "One bedrooms", amount: 1500 },
      { option: "Two bedrooms", amount: 2000 },
      { option: "Whole apartment", amount: 3500 },
      { option: "Monthly Rate", amount: 36000 },
    ],
  },
  {
    id: 2,
    title: "Aburi Mountain Retreat",
    location: "Eastern Region • Aburi",
    coordinates: { lat: 5.843870554138503, lng: -0.17225994962774632 },
    price: 600,
    guests: 4,
    bedrooms: 4,
    hasPool: true,
    bathrooms: 5,
    image: "/Aburi1.jpeg",
    images: ["/Aburi1.jpeg", "/Aburi2.jpeg", "/Aburi3.jpeg", "/Aburi4.jpeg"],
    description:
      "Nestled in the serene and refreshing environment of Aburi, this beautifully furnished apartment offers complete comfort.",
    amenities: [
      "Free Wi-Fi",
      "Kitchen",
      "Pool",
      "Well-furnished hall",
      "Television in all rooms",
    ],
    rates: [
      { option: "Single bedroom", amount: 600 },
      { option: "Studio", amount: 800 },
      { option: "One bedrooms", amount: 1200 },
      { option: "Two bedrooms", amount: 2000 },
      { option: "Whole apartment", amount: 3500 },
      { option: "Monthly Rate", amount: 30000 },
    ],
  },
  {
    id: 3,
    title: "Adenta Serenity",
    location: "Greater Accra • Adenta",
    coordinates: { lat: 5.712737022781674, lng: -0.16226067413187414 },
    price: 600,
    guests: 4,
    bedrooms: 4,
    hasPool: true,
    bathrooms: 5,
    image: "/Adenta1.jpg",
    images: ["/Adenta1.jpg", "/Adenta2.jpg", "/Adenta3.jpg", "/Adenta4.jpg"],
    description:
      "Located in the heart of Adenta, this premium apartment combines luxury, comfort, and entertainment with modern furnishings and a grand piano.",
    amenities: [
      "Free Wi-Fi",
      "Kitchen",
      "Pool",
      "Well-furnished hall",
      "Grand Piano",
      "PS5 Gaming Console",
    ],
    rates: [
      { option: "One bedroom", amount: 1500 },
      { option: "Two bedrooms", amount: 2000 },
      { option: "Whole apartment", amount: 3500 },
      { option: "Monthly Rate", amount: 36000 },
    ],
  },
];
